name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configurar SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SECRET }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 187.86.158.87 >> ~/.ssh/known_hosts

      - name: Enviar arquivos via SCP
        run: |
          rsync -avz --delete --exclude=".env" ./ matheus@187.86.158.87:/home/matheus/web/api.searchpark.com.br/public_html && ssh matheus@187.86.158.87 "cd /home/matheus/web/api.searchpark.com.br/public_html && composer install"
